# Deploy Postgre
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:13.16
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: '256Mi'
              cpu: '125m'
            limits:
              memory: '512Gi'
              cpu: '250m'
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: aula-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: aula-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aula-secrets
                  key: POSTGRES_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
    - port: 5432
      targetPort: 5432
  # type: LoadBalancer
---
# Deploy server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fake-shop
  template:
    metadata:
      labels:
        app: fake-shop
    spec:
      containers:
        - name: fake-shop
          image: albuquerquefabio/kubedev-fake-shop
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: '512Mi'
              cpu: '250m'
            limits:
              memory: '1Gi'
              cpu: '500m'
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: aula-secrets
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: aula-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aula-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: aula-secrets
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: aula-secrets
                  key: DB_PORT

---
apiVersion: v1
kind: Service
metadata:
  name: fake-shop
spec:
  selector:
    app: fake-shop
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
